from collections.abc import Sequence
from typing import Protocol

from app.schemas.portfolio import PortfolioCreateAdm, PortfolioCreatePublic, PortfolioUpdateAdm
from shared.models.portfolio import Portfolio


class PortfolioRepo(Protocol):
    async def create(self, obj_in: PortfolioCreateAdm) -> Portfolio: ...
    async def get_all(self) -> Sequence[Portfolio]: ...
    async def get_by_id(self, portfolio_id: int) -> Portfolio | None: ...
    async def update(self, portfolio: Portfolio, payload: PortfolioUpdateAdm) -> Portfolio: ...
    async def delete(self, portfolio: Portfolio) -> None: ...
    async def get_by_user_id(self, user_id: int) -> Sequence[Portfolio]: ...
    async def create_for_user(self, payload: PortfolioCreatePublic, user_id: int) -> Portfolio: ...
