from collections.abc import Sequence
from typing import Protocol

from app.models import Portfolio, User
from app.models.trade import Trade
from app.schemas.portfolio import PortfolioCreatePublic, PortfolioUpdateAdm
from app.schemas.trade import TradeCreate, TradeUpdate
from app.schemas.user import UserCreateAdm, UserUpdateAdm


class PortfolioRepository(Protocol):
    async def create(self, payload: PortfolioCreatePublic) -> Portfolio: ...
    async def get_all(self) -> Sequence[Portfolio]: ...
    async def get_by_id(self, portfolio_id: int) -> Portfolio | None: ...
    async def update(self, portfolio: Portfolio, payload: PortfolioUpdateAdm) -> Portfolio: ...
    async def delete(self, portfolio: Portfolio) -> None: ...
    async def get_by_user_id(self, user_id: int) -> Sequence[Portfolio]: ...
    async def create_for_user(self, payload: PortfolioCreatePublic, user_id: int) -> Portfolio: ...


class TradeRepoRepository(Protocol):
    async def create(self, obj_in: TradeCreate) -> Trade: ...
    async def get_all(self) -> Sequence[Trade]: ...
    async def get_by_id(self, trade_id: int) -> Trade | None: ...
    async def update(self, trade: Trade, obj_in: TradeUpdate) -> Trade: ...
    async def delete(self, trade: Trade) -> None: ...
    async def get_trades_by_portfolio_id(self, portfolio_id: int) -> Sequence[Trade]: ...
    async def get_trades_by_portfolio_id_for_user(
        self, portfolio_id: int, user_id: int
    ) -> Sequence[Trade]: ...
    async def get_trade_by_id_for_user(self, trade_id: int, user_id: int) -> Trade: ...


class UserRepoRepository(Protocol):
    async def create(self, obj_in: UserCreateAdm) -> User: ...
    async def get_all(self) -> Sequence[User]: ...
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def update(self, user: User, obj_in: UserUpdateAdm) -> User: ...
    async def delete(self, user: User) -> None: ...
