"""numeric

Revision ID: 3bb7dd94cc28
Revises: 358f273610ac
Create Date: 2026-01-26 21:48:55.410184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb7dd94cc28'
down_revision: Union[str, Sequence[str], None] = '358f273610ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_prices', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_prices', 'price',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
