"""add column currency into portfolio

Revision ID: 835d78d3b012
Revises: 49d6a540d836
Create Date: 2025-11-30 02:24:21.338373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835d78d3b012'
down_revision: Union[str, Sequence[str], None] = '49d6a540d836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('currency', sa.Text(), nullable=False, server_default='RUB'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'currency')
    # ### end Alembic commands ###
