"""add email and pwd to user

Revision ID: fb3b6d3eeee3
Revises: d8e0dacfdb83
Create Date: 2025-12-27 18:19:53.993267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3b6d3eeee3'
down_revision: Union[str, Sequence[str], None] = 'd8e0dacfdb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False, server_default='test@test.test'))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False, server_default='test'))
    op.alter_column('users', 'email', server_default=None)
    op.alter_column('users', 'password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
